baseURL = "https://pcsjbsa.us/"
languageCode = "en-us"
title = "Moving to San Antonio?"
description = "Information for military members moving to San Antonio."
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
    [markup.goldmark.renderer]
        # Needed for mermaid shortcode
        unsafe = true
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 9

# Options
[params]
    geekdocLogo = "alamo.svg"
    geekdocRepo = "https://github.com/kc0bfv/sanantonio.notmet.net"
    geekdocEditPath = "edit/main"
    geekdocListUseTOC = true
    [params.geekdocContentLicense]
        name = "CC BY-SA 4.0"
        link = "https://creativecommons.org/licenses/by-sa/4.0/"